# Mini Trackball Keyboard Configuration
# Hardware: PWM3610 trackball, EC11 encoder, 2x switches
# MCU: Nice!nano v2

# Board configuration
CONFIG_ZMK_KEYBOARD_NAME="Mini Trackball"

# Enable mouse support
CONFIG_ZMK_MOUSE=y

# PWM3610 Trackball Configuration (from menbou0202/zmk-config-nape)
CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_PMW3610=y
CONFIG_PMW3610_INVERT_X=y
CONFIG_PMW3610_ORIENTATION_90=y
CONFIG_PMW3610_INVERT_SCROLL_X=n
CONFIG_PMW3610_INVERT_SCROLL_Y=y
CONFIG_PMW3610_CPI=3200
CONFIG_PMW3610_CPI_DIVIDOR=4
CONFIG_PMW3610_SNIPE_CPI=1200
CONFIG_PMW3610_SNIPE_CPI_DIVIDOR=4
CONFIG_PMW3610_SCROLL_TICK=150
CONFIG_PMW3610_POLLING_RATE_125_SW=y
CONFIG_PMW3610_SMART_ALGORITHM=y

# Power management
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000 