# Mini Trackball Keyboard Configuration
# Hardware: PWM3610 trackball, EC11 encoder, 2x switches
# MCU: Nice!nano v2

# Board configuration
CONFIG_ZMK_KEYBOARD_NAME="Mini Trackball"
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Nice!nano specific settings
CONFIG_ZMK_USB=y
CONFIG_ZMK_BLE=y
CONFIG_ZMK_EXT_POWER=y

# Enable trackball
CONFIG_ZMK_MOUSE=y
CONFIG_PMW3610=y
CONFIG_PMW3610_CS_PIN=4
CONFIG_PMW3610_DR_PIN=5
CONFIG_PMW3610_MOTION_PIN=6

# Enable encoder
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Enable RGB (optional)
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_WS2812_STRIP=y
CONFIG_ZMK_RGB_UNDERGLOW_SPD_START=3

# Power management
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000 